---
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=py36-django20-wagtail20
    - python: 3.6
      env: TOXENV=py36-django20-wagtail21

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov
